### ISSUE TITLE
Mistake in specification

### ISSUE THREAD

**Issue by mikakruschel** [DeepLcom/openapi#1]
Hey, I think I spotted a mistake in the specification. I'm new to the OpenAPI but if I understand it correctly, the specification currently says the `detected_source_language` conforms to two types: `SourceLanguage` and a type with only a description (line 205) and thus any content(?).
https://github.com/DeepLcom/openapi/blob/70671833a5f8f498fd4fa9fb27e266fb091b468a/openapi.json#L199-L208

I believe the section instead should be:
```json
"detected_source_language": {
    "allOf": [
      {
        "$ref": "#/components/schemas/SourceLanguage"
      }
    ],
    "description": "The language detected in the source text. It reflects the value of the `source_lang` parameter, when specified."
  },
```

I'm not sure if the yaml file also needs to be fixed.

**Comment by daniel-jones-deepl** [comment]
Hi @mikakruschel, sorry this reply is so delayed. Thanks for pointing this out. I think we can fix this soon.

**Comment by seekuehe** [comment]
The fix will be part of the next update
